"""
reporter.py — Parses captures.log and generates an HTML awareness report
              showing who submitted credentials and when.
"""

import json
from datetime import datetime
from collections import Counter
from pathlib import Path

REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{campaign} — PhishSim Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #f5f5f5; color: #1a1a1a; padding: 40px 20px;
  }}
  .container {{ max-width: 860px; margin: 0 auto; }}
  h1 {{ font-size: 24px; font-weight: 600; margin-bottom: 4px; }}
  .sub {{ font-size: 14px; color: #666; margin-bottom: 32px; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 16px; margin-bottom: 32px; }}
  .stat {{ background: #fff; border-radius: 10px; padding: 20px;
    border: 0.5px solid #e0e0e0; }}
  .stat-label {{ font-size: 12px; color: #888; text-transform: uppercase;
    letter-spacing: 0.06em; margin-bottom: 6px; }}
  .stat-value {{ font-size: 28px; font-weight: 600; }}
  .stat-value.red {{ color: #c53030; }}
  .section-title {{ font-size: 14px; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.06em; color: #888; margin-bottom: 12px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
    border-radius: 10px; overflow: hidden; border: 0.5px solid #e0e0e0;
    margin-bottom: 32px; font-size: 13px; }}
  th {{ background: #f9f9f9; text-align: left; padding: 10px 16px;
    border-bottom: 1px solid #eee; font-weight: 500; color: #555; }}
  td {{ padding: 10px 16px; border-bottom: 0.5px solid #f0f0f0;
    vertical-align: top; font-family: monospace; font-size: 12px; }}
  tr:last-child td {{ border-bottom: none; }}
  .fields {{ background: #f8f8f8; border-radius: 6px; padding: 8px 12px;
    white-space: pre-wrap; word-break: break-all; }}
  .ua {{ color: #999; font-size: 11px; }}
  .disclaimer {{
    background: #fff8f0; border: 1px solid #f6ad55; border-radius: 8px;
    padding: 16px 20px; font-size: 13px; color: #744210; margin-bottom: 32px;
    line-height: 1.6;
  }}
  .disclaimer strong {{ display: block; margin-bottom: 4px; }}
  .timeline {{ background: #fff; border-radius: 10px; padding: 20px;
    border: 0.5px solid #e0e0e0; margin-bottom: 32px; }}
  .bar-row {{ display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }}
  .bar-label {{ font-size: 12px; color: #555; width: 160px; flex-shrink: 0;
    white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }}
  .bar-track {{ flex: 1; background: #f0f0f0; border-radius: 4px; height: 14px; }}
  .bar-fill {{ height: 100%; border-radius: 4px; background: #e53e3e; }}
  .bar-count {{ font-size: 12px; color: #888; width: 28px; text-align: right; }}
  footer {{ font-size: 11px; color: #bbb; text-align: center; margin-top: 16px; }}
</style>
</head>
<body>
<div class="container">
  <h1>{campaign}</h1>
  <p class="sub">Generated {generated_at} — PhishSim awareness report</p>

  <div class="disclaimer">
    <strong>AUTHORIZED TEST — CONFIDENTIAL</strong>
    This report was generated by an authorized security awareness simulation.
    Data must be handled in accordance with your organization's privacy policy.
    No credentials were transmitted outside the test environment.
  </div>

  <div class="stats">
    <div class="stat">
      <div class="stat-label">Total captures</div>
      <div class="stat-value red">{total_captures}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Unique IPs</div>
      <div class="stat-value">{unique_ips}</div>
    </div>
    <div class="stat">
      <div class="stat-label">First capture</div>
      <div class="stat-value" style="font-size:16px">{first_capture}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Last capture</div>
      <div class="stat-value" style="font-size:16px">{last_capture}</div>
    </div>
  </div>

  <p class="section-title">Captures by IP</p>
  <div class="timeline">
    {ip_bars}
  </div>

  <p class="section-title">Capture log</p>
  <table>
    <thead>
      <tr>
        <th>Timestamp (UTC)</th>
        <th>IP Address</th>
        <th>Submitted fields</th>
      </tr>
    </thead>
    <tbody>
      {table_rows}
    </tbody>
  </table>

  <footer>PhishSim — for authorized security awareness testing only</footer>
</div>
</body>
</html>
"""


def _parse_log(log_file: str) -> list:
    entries = []
    with open(log_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return entries


def _format_fields(fields: dict) -> str:
    if not fields:
        return "(no fields captured)"
    return "\n".join(f"{k}: {v}" for k, v in fields.items())


def _ip_bars(ip_counter: Counter, total: int) -> str:
    if not ip_counter:
        return "<p style='color:#888;font-size:13px'>No captures yet.</p>"
    bars = []
    for ip, count in ip_counter.most_common(20):
        pct = int((count / total) * 100)
        bars.append(f"""
        <div class="bar-row">
          <span class="bar-label">{ip}</span>
          <div class="bar-track">
            <div class="bar-fill" style="width:{pct}%"></div>
          </div>
          <span class="bar-count">{count}</span>
        </div>""")
    return "".join(bars)


def generate_report(log_file: str, output_path: str, campaign: str = "Phishing Awareness Test") -> int:
    entries = _parse_log(log_file)
    total = len(entries)

    if total == 0:
        timestamps = ["—"]
        unique_ips = 0
        first_ts = last_ts = "—"
        ip_counter = Counter()
    else:
        timestamps = [e["timestamp"] for e in entries]
        timestamps.sort()
        first_ts = timestamps[0][:19].replace("T", " ")
        last_ts = timestamps[-1][:19].replace("T", " ")
        ip_counter = Counter(e["ip"] for e in entries)
        unique_ips = len(ip_counter)

    table_rows = ""
    for e in entries:
        ts = e.get("timestamp", "")[:19].replace("T", " ")
        ip = e.get("ip", "")
        ua = e.get("user_agent", "")
        fields_html = f'<div class="fields">{_format_fields(e.get("fields", {}))}</div>'
        if ua:
            fields_html += f'<div class="ua">{ua}</div>'
        table_rows += f"<tr><td>{ts}</td><td>{ip}</td><td>{fields_html}</td></tr>\n"

    html = REPORT_TEMPLATE.format(
        campaign=campaign,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        total_captures=total,
        unique_ips=unique_ips if total else 0,
        first_capture=first_ts if total else "—",
        last_capture=last_ts if total else "—",
        ip_bars=_ip_bars(ip_counter, total),
        table_rows=table_rows or "<tr><td colspan='3' style='color:#bbb;text-align:center;padding:24px'>No captures yet.</td></tr>",
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return total
